/**
 * Tests for the prompt-builder plugin node.
 *
 * Exercises the node against a real NodeContext (from @aituber-flow/sdk).
 * `promptSections` is normally generated by the editor UI (Canvas.tsx / the
 * prompt-builder field renderer in NodeSettings.tsx) but the node itself only
 * cares about the shape: an array of { type: "text" | "input", content }.
 */

import { describe, it, expect } from "bun:test";
import { NodeContext } from "../../packages/sdk-ts/src/context";
import PromptBuilderNode from "../../plugins/prompt-builder/node";

function createContext() {
  const logs: Array<{ message: string; level: string }> = [];
  const ctx = new NodeContext({
    workflowId: "wf-1",
    nodeId: "prompt-builder-1",
    character: {},
    logCallback: async (message, level) => {
      logs.push({ message, level: level ?? "info" });
    },
  });
  return { ctx, logs };
}

describe("PromptBuilderNode", () => {
  it("joins text-only sections into the system prompt", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      {
        promptSections: [
          { type: "text", content: "You are a helpful assistant." },
          { type: "text", content: "Always answer in Japanese." },
        ],
      },
      ctx,
    );

    const result = await node.execute({}, ctx);

    expect(result).toEqual({
      system: "You are a helpful assistant.\nAlways answer in Japanese.",
    });
  });

  it("substitutes an input section with a plain string value", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      {
        promptSections: [
          { type: "text", content: "Context:" },
          { type: "input", content: "input_1" },
        ],
      },
      ctx,
    );

    const result = await node.execute({ input_1: "the user likes cats" }, ctx);

    expect(result).toEqual({ system: "Context:\nthe user likes cats" });
  });

  it("extracts .text from an object input value", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      { promptSections: [{ type: "input", content: "input_1" }] },
      ctx,
    );

    const result = await node.execute(
      { input_1: { text: "subtitle text", extra: "ignored" } },
      ctx,
    );

    expect(result).toEqual({ system: "subtitle text" });
  });

  it("extracts .message from an object input value", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      { promptSections: [{ type: "input", content: "input_1" }] },
      ctx,
    );

    const result = await node.execute(
      { input_1: { message: "chat message text" } },
      ctx,
    );

    expect(result).toEqual({ system: "chat message text" });
  });

  it("JSON-stringifies an array input value", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      { promptSections: [{ type: "input", content: "input_1" }] },
      ctx,
    );

    const result = await node.execute(
      { input_1: ["one", "two", "three"] },
      ctx,
    );

    expect(result).toEqual({ system: JSON.stringify(["one", "two", "three"]) });
  });

  it("JSON-stringifies an object input value with neither .text nor .message", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      { promptSections: [{ type: "input", content: "input_1" }] },
      ctx,
    );

    const result = await node.execute(
      { input_1: { foo: "bar" } },
      ctx,
    );

    expect(result).toEqual({ system: JSON.stringify({ foo: "bar" }) });
  });

  it("treats a missing input value as an empty string", async () => {
    const { ctx } = createContext();
    const node = new PromptBuilderNode();
    await node.setup(
      { promptSections: [{ type: "input", content: "input_1" }] },
      ctx,
    );

    const result = await node.execute({}, ctx);

    expect(result).toEqual({ system: "" });
  });

  it("logs a warning and returns an empty system prompt when no sections are configured", async () => {
    const { ctx, logs } = createContext();
    const node = new PromptBuilderNode();
    await node.setup({ promptSections: [] }, ctx);

    const result = await node.execute({}, ctx);

    expect(result).toEqual({ system: "" });
    expect(logs.some((l) => l.level === "warning" && l.message.includes("No prompt sections"))).toBe(
      true,
    );
  });

  it("defaults to an empty section list when promptSections is missing from config", async () => {
    const { ctx, logs } = createContext();
    const node = new PromptBuilderNode();
    await node.setup({}, ctx);

    const result = await node.execute({}, ctx);

    expect(result).toEqual({ system: "" });
    expect(logs.some((l) => l.level === "warning")).toBe(true);
  });
});
